# Makefile
.PHONY: run hash clean

# Uruchamia program z parametrami <HASH> <DŁUGOŚĆ>
run:
	python3 main.py d17bf024d6ee0527ced15648cedf2e5c710a2fc2b24aec5c7549159a14c7732d 4

# Generuje hash dla podanego w pliku tekstu
hash:
	python3 hash.py

# Czyści pliki tymczasowe
clean:
	rm -rf __pycache__ *.pyc